### ISSUE TITLE
Firefox選擇頭像點擊功能失效

### ISSUE THREAD

**Issue by iceice666** [SmartRTE/SmartRTE.github.io#2]
在當前版本[c8ded1b](https://github.com/SmartRTE/SmartRTE.github.io/commit/c8ded1ba67120f2418e67ad9f482e495d45a6d08)中 
Firefox端的選擇頭像點擊功能失效

經測試，[f962aab](https://github.com/SmartRTE/SmartRTE.github.io/commit/f962aab731d2ba4d21b9f87dff0382ed1e168827) 這個版本是正常運作的

經過Firefox降級(118.0.1=>117.0.1)後排除是Firefox的鍋的可能性

目前 chromium 系的瀏覽器是正常的

(我會慢慢排查 不過台灣這邊高中還有一個禮拜要段考 所以結果可能會沒這麼快)

UP 加油 要對自己的代碼有自信! :D

**Comment by SmartRTE** [comment]
感谢查错！查明了原因是Firefox对position: absolute的处理 与Chrome不同，现调回relative，测试Firefox(116.0.3 和 118.0.1版本)，以及Firefox for Android都可以正常更换头像了

另祝学习加油考试顺利喔 :D
