### ISSUE TITLE
上传实际有数据的st3文件提示无数据

### ISSUE THREAD

**Issue by ShimoKage** [SmartRTE/SmartRTE.github.io#3]
如题，因为github无法上传db格式文件我将压缩后上传
[st3.zip](https://github.com/SmartRTE/SmartRTE.github.io/files/15322821/st3.zip)
![1715782817886](https://github.com/SmartRTE/SmartRTE.github.io/assets/111337161/926b6e70-9a15-43ce-bb12-fa9489bd99ed)
![image](https://github.com/SmartRTE/SmartRTE.github.io/assets/111337161/a2b81c84-c3f7-4f32-b375-8533ff55847c)

**Comment by Orirock** [comment]
补个图
![Uploading image.png…]()

**Comment by ShimoKage** [comment]
因为条件有限，无法使用其他st3文件测试，但是我这个st3经过多次测试确实无法查询

**Comment by SmartRTE** [comment]
看起来可能是你的游戏版本不太对劲🤔所有的songId前面都有official/的前缀。我的设计是以songId作为主键，sql查询语句执行时按照songId进行连接，导致不匹配，获取到的查询结果为空
![image](https://github.com/SmartRTE/SmartRTE.github.io/assets/105839881/b706cf11-c3c9-4600-a383-109f415e300c)

作为参照，官方v5.6.0c版本的游戏对应目录下的st3数据库的scores表是下面这样的：
![image](https://github.com/SmartRTE/SmartRTE.github.io/assets/105839881/4a409c56-6741-4bd3-9b25-411f65aa70ec)
可以进行正常查询。

如果你是在其他渠道下载的，或者是“魔改版”，可能在songlist里定义的songId与官方版本不同，所以用不了🤔
不过既然有PC，可以尝试用下面的语句将songId中的前缀去除：

```
UPDATE your_table_name
SET songId = REPLACE(songId, 'official/', '');
```

执行成功，之后再在页面上选择这个st3就可以正常进行查询和显示了：
![image](https://github.com/SmartRTE/SmartRTE.github.io/assets/105839881/b164b531-7329-43c1-ba0c-ee4c950b9bf3)

**Comment by ShimoKage** [comment]
谢谢大佬
